name: build
on:
  push:
jobs:
  build:
    runs-on:
      - linux
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - run: corepack enable
      - name: Install Dependencies
        run: yarn install
      - name: Build Packages and Apps
        run: yarn build:ci
      - name: Test Packages and Apps
        run: yarn test:ci
