name: build
on:
  push:
jobs:
  build:
    runs-on:
      - linux
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: corepack enable
      - name: Configure caching
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: yarn
      - name: Install Dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
